openapi: 3.0.0
info:
  version: 1.0.0
  title: E-Szuri API
  description: REST API paths
servers:
  - url: http://localhost:3000
paths:
  /person/count/json:
    get:
      description: Returns numbers of persons
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Number of persons returned successfully
          content:
            application/json:
              schema:
                type: number
                items:
                  $ref: ''
        
    
  /person/vaccinated/json:
    get:
      description: Returns persons
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of persons returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ''
        
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Person:
      type: object
      required:
        - id
        - firstName
        - lastName
        - vaccine
      properties:
        id: number
        firstName:
          type: string
        lastName:
          type: string
        vaccine:
          type: string